import { Entity } from "@/types/common";
import { Chart as BarChart, DiagramUp as AreaChart, RoundGraph, HashtagSquare } from "solar-icon-set";

export type Item = { icon: any; label: string; type: Entity; subType: string; img?: string };

export const CHARTS: Item[] = [
  { label: "Area chart", icon: AreaChart, type: "CHART", subType: "AREA", img: "/images/charts/line.svg" },
  { label: "Bar chart", icon: BarChart, type: "CHART", subType: "BAR", img: "/images/charts/bar.svg" },
  { label: "Pie chart", icon: RoundGraph, type: "CHART", subType: "PIE", img: "/images/charts/line.svg" },
];

export const WIDGETS: Item[] = [
  { label: "Table", icon: HashtagSquare, type: "WIDGET", subType: "table" },
  { label: "Text", icon: HashtagSquare, type: "WIDGET", subType: "text" },
];

export const metaMetricsKeys = [
  "spend",
  "reach",
  "ctr",
  "unique_ctr",
  "cpm",
  "cpr",
  "roas",
  "impression",
  "clicks",
  "unique_clicks",
  "lead",
  "cost_per_lead",
  "link_clicks",
  "unique_link_clicks",
  "video_view",
  "video_thru_view",
  "hook_rate",
  "hold_rate",
  "cost_per_unique_link_click",
  "cost_per_add_to_cart",
  "app_install",
  "cost_per_app_install",
  "message_conversation_started",
  "metric",
  "cost_per_purchase",
  "landing_page_views",
  "unique_landing_page_views",
  "cost_per_landing_page_view",
  "add_to_cart",
  "mobile_app_activation",
  "cost_per_activation",
  "checkout_initiated",
  "cost_per_checkout_initiated",
  "mobile_purchase",
  "page_engagement",
  "application_submitted",
  "cost_per_application_submitted",
  "credit_spent",
  "cost_per_credit_spend",
  "registration_completed",
  "purchase",
  "results",
  "cost_per_message",
  "message",
  "cost_per_link_clicks",
  "cost_per_clicks",
  "offline_subscription",
  "website_subscription",
  "mobile_app_subscription",
  "app_custom_event_fb_mobile_search",
  "find_location_offline",
  "offsite_conversion_fb_pixel_add_to_wishlist",
  "onsite_conversion_flow_complete",
  "omni_custom_metric",
  "cost_per_location_search",
  "cost_per_registration_completed",
  "find_location_total",
  "mobile_achievement_unlocked",
  "cost_per_mobile_achievement_unlocked",
];

export const campaignMetricsTitleMap: Record<string, string> = {
  spend: "Amount Spent",
  impression: "Impressions",
  cpm: "CPM",
  ctr: "CTR",
  // cpc: "CPC",
  cost_per_message: "Cost per Message",
  message: "Messages",
  reach: "Reach",
  results: "Results",
  cpr: "Cost per Result",
  purchase: "Purchase",
  roas: "ROAS",
  clicks: "Clicks",
  conversions: "Conversions",
  offline_subscription: "Offline Subscription",
  website_subscription: "Website Subscription",
  mobile_app_subscription: "Mobile App Subscription",
  app_custom_event_fb_mobile_search: "Mobile App Custom Event Search",
  find_location_offline: "Find Location Offline",
  offsite_conversion_fb_pixel_add_to_wishlist: "Offsite Conversion (Add to Wishlist)",
  onsite_conversion_flow_complete: "Onsite Conversion (Flow Complete)",
  omni_custom_metric: "Omni Custom Metric",
  cost_per_location_search: "Cost per Location Search",
  unique_ctr: "Unique CTR",
  unique_clicks: "Unique Clicks",
  lead: "Lead",
  cost_per_lead: "Cost per Lead",
  link_clicks: "Link Clicks",
  unique_link_clicks: "Unique Link Clicks",
  cost_per_unique_link_click: "Cost per Unique Link Click",
  cost_per_add_to_cart: "Cost per Add to Cart",
  app_install: "App Install",
  cost_per_app_install: "Cost per App Install",
  message_conversation_started: "Message Conversation Started",
  metric: "Metric",
  cost_per_purchase: "Cost per Purchase",
  landing_page_views: "Landing Page Views",
  unique_landing_page_views: "Unique Landing Page Views",
  cost_per_landing_page_view: "Cost per Landing Page View",
  add_to_cart: "Add to Cart",
  mobile_app_activation: "Mobile App Activation",
  cost_per_activation: "Cost per Activation",
  checkout_initiated: "Checkout Initiated",
  cost_per_checkout_initiated: "Cost per Checkout Initiated",
  mobile_purchase: "Mobile Purchase",
  page_engagement: "Page Engagement",
  post_engagement: "Post Engagement",
  application_submitted: "Application Submitted",
  cost_per_application_submitted: "Cost per Application Submitted",
  credit_spent: "Credit Spent",
  cost_per_credit_spend: "Cost per Credit Spent",
  registration_completed: "Registration Completed",
  cost_per_registration_completed: "Cost per Registration Completed",
  find_location_total: "Find Location Total",
  mobile_achievement_unlocked: "Mobile Achievement Unlocked",
  cost_per_mobile_achievement_unlocked: "Cost per Mobile Achievement Unlocked",
  cost_per_link_clicks: "Cost per link clicks",
  // cost_per_clicks: "Cost per clicks",
  cost_per_clicks: "CPC",
  video_view: "Video view",
  video_thru_view: "Video through view",
  hook_rate: "Hook rate",
  hold_rate: "Hold rate",
};

export const METRICS: Item[] = metaMetricsKeys.map((item) => ({ label: campaignMetricsTitleMap[item], icon: HashtagSquare, type: "METRIC", subType: item }));
